### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by grifas** [ShengHuaWu/Vapor3Series#1]
Thanks you for the series !

But I'm facing an issue and I didn't see an approach on the net. 

I would like to get a nested json response like:
```
{
 "age": 23,
 "id": 1,
 "user": {
    "user_id": 0,
    "name": "myName"
 }
} 
```

So my question is how to return a nested json ? Thank you

**Comment by ShengHuaWu** [comment]
Hi @grifas,

Sorry for my super late reply. 😞 

Vapor supports nested JSON too. 🙂 
You can do something like the following
```
struct NestedJSON: Codable {
    struct UserInfo: Codable {
        // Support snake_case with `CodingKeys`...
        let id: Int
        let name: String
    }

    let id: Int
    let age: Int
    let user: UserInfo
}

extension NestedJSON: Content {}
// ...
```
